services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Required for the docker-containers widget (read-only)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "xxxx:8080"
    env_file: .env
